### ISSUE TITLE
 Error: Compilation of µWebSockets has failed

### ISSUE THREAD

**Issue by GoorLavi** [jhen0409/react-native-boilerplate#25]
hey i cannot use npm start    
 
windows10
 i did:
```
git clone 
npm install -g react-native-cli
cd ....
npm i
```

and the output is:
1534688399469 - Origin: Worker (PID 60412)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (C:\Users\goorlavi1\Documents\MathIt-Native\node_modules\uws\uws.js:38:19)
    at Object.<anonymous> (C:\Users\goorlavi1\Documents\MathIt-Native\node_modules\uws\uws.js:42:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new SCServer (C:\Users\goorlavi1\Documents\MathIt-Native\node_modules\socketcluster-server\scserver.js:96:18)
1534688399481 - Worker 0 exited - Exit code: 1

this error happends few times in a second.

i have tried to re-install uws module and clean npm cache or installing via generator

**Comment by GoorLavi** [comment]
Solved by updating package to latest
